---
- name: Tests f√ºr Windows Server 2022
  hosts: windows
  vars_files:
    - vars/main.yml

  roles: 
    - users
    - iis
    - failoverclustering
    - sqlpsmodule
    - sqlserver2022
    - ssms