---
- name: Tests f√ºr Windows Server 2022
  hosts: windows
  collections:
    - ansible.windows
    - community.windows
  vars_files:
    - vars/main.yml

  roles: 
    - failoverclustering
  #  - sqlserver2022
  #  - users
  #  - iis
  #  - ssms
  #  - sqlpsmodule