---
- name: add local
  win_user:
    name: "{{ username }}"
    password: "{{ password }}"
    state: present
    groups:
      - Users
    description: "created with Ansible"
    password_never_expires: yes
    user_cannot_change_password: no

- name: make user local admin
  win_group_membership:
    name: Administrators
    members: 
      -  "{{ username }}"
    state: present