---
- name: install dir
  win_file:
    path: C:\Install
    state: directory
  
- name: download ssms installer
  win_get_url:
    url: "{{ ssms_installer_url }}"
    dest: "{{ ssms_installer_path }}"
    force: no

- name: install ssms
  win_command: >
    "{{ ssms_installer_path }}" /Install /Quiet /Norestart
  args:
    chdir: C:\Install
  register: ssms_install